name: YTD Release

on: 
  push:
    paths:
      - "*.py"
  workflow_dispatch:


jobs:

  build:
    runs-on: windows-latest
    name: Build YTD
    outputs:
      full_sha: ${{ steps.var.outputs.full_sha }}

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Crate Build Environment
      run: echo PATH=${GITHUB_WORKSPACE}/.venv/bin:$PATH >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pyinstaller
        pip install -r requirements.txt

    - name: Install UPX
      run: |
        Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-win64.zip" -OutFile "./upx.zip"
        Expand-Archive -Path "./upx.zip" -DestinationPath "./upx"

    - name: Review Code With Flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Build Executable
      run: |
        pyinstaller "main.py" --noconfirm --onefile --windowed --name "YouTube-Downloader" --clean --version-file "./version.txt" --icon "./src/assets/img/ytd_icon.ico" --splash "./src/assets/img/ytd_splash.png" --add-data "./src;src/" --add-binary "./src/assets/dll/glfw3.dll;." --add-binary "./src/assets/dll/msvcr110.dll;." --upx-dir "./upx" --upx-exclude "vcruntime140.dll"

    - name: Generate Build Info
      id: var
      run: |
        echo "full_sha=$(git rev-parse HEAD)" >> $env:GITHUB_OUTPUT
        echo "short_sha=$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary
        path: |
          dist\YouTube-Downloader.exe

  create_release:
    runs-on: ubuntu-latest
    name: Delete Old Release
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Delete Old Release
        id: delete_old_release
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const tag = "YTD";
            const releases = await github.rest.repos.listReleases({
              owner: owner,
              repo: repo,
            });

            const release = releases.data.find(release => release.tag_name === tag);
            if (release) {
              await github.rest.repos.deleteRelease({
                owner: owner,
                repo: repo,
                release_id: release.id,
              });
              console.log(`Deleted release with ID ${release.id}`);
            } else {
              console.log("No existing release to delete");
            }

            try {
              await github.rest.git.deleteRef({
                owner: owner,
                repo: repo,
                ref: `tags/${tag}`,
              });
              console.log(`Deleted tag ${tag}`);
            } catch (error) {
              console.error(`Error deleting tag: ${error.message}`);
            }

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: binary
        
      - name: Echo build_sha256
        id: build_sha
        run: |
          sha256sum YouTube-Downloader.exe > sha256.checksum
          echo "build_sha=$(cat sha256.checksum)" >> $GITHUB_OUTPUT
          cat sha256.checksum

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          name: YouTube Downloader
          tag_name: "YTD"
          body: |
              >[!NOTE]
              >**This automatic release was built by Github Actions**
              >| [Link to build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) |
              >| ------------- |
          files: |
            YouTube-Downloader.exe
